name: Publish Unit Test Coverage
on:
  workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@rc
        with: 
          egress-policy: audit
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          
      - name: Test & generate JaCoCo XML
        working-directory: engine
        run: mvn --no-transfer-progress --batch-mode -q clean test jacoco:report
      
      - name: Upload coverage with Coveralls Universal Reporter (no-fail)
        working-directory: engine
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          curl -sSL https://coveralls.io/coveralls-linux.tar.gz | tar -xz
          ./coveralls report \
            --file target/site/jacoco/jacoco.xml \
            --no-fail
